name: 'airport_practice'
version: '1.0.0'
config-version: 2
profile: 'airport_practice'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  airport_practice:
    +post-hook:
      - |
          CREATE SCHEMA IF NOT EXISTS logs;

          CREATE TABLE IF NOT EXISTS {{ target.database }}.logs.dbt_logs (
              event_date timestamp,
              event_name varchar(100),
              node_name varchar(255)
          );

          INSERT INTO {{ target.database }}.logs.dbt_logs
          (event_date, event_name, node_name)
          VALUES (
              CURRENT_TIMESTAMP, 'run model', '{{ model.name }}'
          );
      - "{{ check_dependencies(model.name) }}"

    intermediate:
      flights:
        meta:
          owner: "egorovmaxkrd@gmail.com"
          year_created: 2026
        +tags: ["intermediate"]

    staging:
      +tags: ["staging"]

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"
